[[services]]
urlDest = "http://danielddsv.com.br/movie_store/lancamentos"
urlSrc = "/exemplo1"
host ="localhost"
method = "GET"
type = "application/json"
queryParam =""


[[services]]
urlDest = "http://danielddsv.com.br/movie_store/generos/tipos/total"
urlSrc = "/exemplo6"
host ="localhost"
method = "GET"
type = "application/json"
queryParam =""

[[services]]
urlDest = "http://danielddsv.com.br/movie_store/email/sendContato"
urlSrc = "/exemplo10"
host ="localhost"
method = "POST"
type = "application/json"
queryParam =""
