[[services]]
urlDest = "http://google.com"
urlSrc = "/exemplo1"
ip ="1233"
host ="localhost"
method = "GET"
type = "json/application"
queryParam =""

[[services]]
urlDest = "/exemplo2"
urlSrc = "/exemplo1"
ip ="1233"
host ="localhost"
method = "GET"
type = "json/application"
queryParam =""


[[services]]
url = "/exemplo3"
urlSrc = "/exemplo1"
ip ="1233"
host ="localhost"
method = "GET"
type = "json/application"
queryParam =""

[[services]]
url = "/exemplo4"
urlSrc = "/exemplo1"
ip ="1233"
host ="localhost"
method = "GET"
type = "json/application"
queryParam =""
